version: '3'
services:
  api:
    build: .
    ports:
      - "3333:3333"
    environment:
      - RAQUETTE_HOST=raquettekvs
      - TENNIS_HOST=tenniskvs
    depends_on:
      - redis
  
  tennis-redis:
    image: redis
    hostname: tenniskvs
    volumes:
      - tennis-data:/data
  
  raquette-redis:
    image: redis
    hostname: raquettekvs
    volumes:
      - raquette-data:/data

volumes:
  tennis-data:
  raquette-data:
